version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<your_db_password>
      - POSTGRES_DB=Serialization  #image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A my_project worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=my_project.settings
      - REDIS_URL=redis://redis:6379/0  # points to the redis container
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A my_project beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=my_project.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  web:
    build: .
    command: gunicorn my_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=my_project.settings
      - DATABASE_URL=postgres://postgres:<your_db_password>@db:5432/Serialization # points to the db container
    depends_on:
      - db
    volumes:
      - .:/app
      - ./media:/app/media # Mount media folder
